routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//use Illuminate\Routing\Route;
//use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect()->to('/login');
})->name('index');


Route::get('password/reset', [
    'as' => 'password.request',
    'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm'
]);

Route::get('/campaign', 'HomeController@index')->name('campaign');
Route::get('/influencer/account/{token}', 'frontend\InfluenceruserController@updateAccountStatus')->name('updateStatusAccount');

Route::get('connect', 'backend\TwitterController@connect');
Route::get('connectfb', 'backend\FacebookController@connect');
Route::post('getFacebookSession', 'backend\FacebookController@sessionData');
Route::post('getFacebookuser', 'backend\FacebookController@getFacebookuser');
Route::get('/redirecttwitter', 'SocialAuthTwitterController@redirect');
Route::get('/callbackUrl', 'SocialAuthTwitterController@callbackUrl');
Route::post('getSession', 'backend\TwitterController@sessionData');
Route::get('twittercallback', 'backend\TwitterController@callback')->name('twitter.callback');

Route::group(['namespace'=>'Auth'], function () {
    Route::post('/register/influencer', 'RegisterController@store')->name('register.influencer.user');  
    Route::get('/mail', 'RegisterController@mail')->name('mail');
    Route::get('/aa', 'RegisterController@aa')->name('aa');
    Route::get('/verifyMail', 'RegisterController@verifyMail')->name('verifyMail');
    Route::get('/adminVerifyMail', 'RegisterController@adminVerifyMail')->name('adminVerifyMail');
    Route::get('/influencer/register/', 'RegisterController@showRegistrationForm')->name('registerInf');
    Route::get('/redirect', 'FacebookController@redirect');
    Route::get('/callback', 'FacebookController@callback');
    Route::get('/city', 'RegisterController@getCity')->name('getCity');
});
Auth::routes();

Route::group(['middleware' => 'influencerUser','namespace'=>'frontend'], function () {
    Route::get('influencer/history/', 'InfluenceruserController@history')->name('influenceruser.history');
    Route::get('edit/profile/{id}', 'InfluenceruserController@edit')->name('influenceruser.edit');
    Route::post('/edit', 'InfluenceruserController@update')->name('influenceruser.update');
    Route::post('influencer/cp/', 'InfluenceruserController@changePassword')->name('influenceruser.cp');
    Route::get('facebookShare/verify/','InfluenceruserController@shareVerify')->name('facebookShare.verify');
    Route::post('twitter/verify/', 'InfluenceruserController@shareVerify')->name('twitter.verify');
    Route::post('fetch/cities/', 'InfluenceruserController@fetchCities')->name('influenceruser.fetchCities');
    Route::get('faq', 'InfluenceruserController@influenceruserFaq')->name('faq');
});

//Route::get('getFeed', 'backend\FacebookController@getFeed');
Route::group(['middleware' => 'influencerUser','namespace'=>'backend'], function () {
    Route::get('sharePost', 'FacebookController@shareCamping')->name('share');
    Route::get('shareTweet', 'TwitterController@shareTweet')->name('shareTweet');
    Route::get('postTweet/{id}', 'TwitterController@postTweet')->name('postTweet');
    Route::get('shareValidate', 'TwitterController@validateTweet')->name('validateTweet');
    Route::get('error', 'TwitterController@error')->name('twitter.error');
    Route::get('add_channel', 'TwitterController@addChannel')->name('twitter.add');
    Route::get('/remove/fb', 'FacebookController@removeChannel')->name('remove.fb.channel');
    Route::get('/remove/twitter', 'TwitterController@removeChannel')->name('remove.twitter.channel');
    Route::get('/remove_session', 'TwitterController@removeSession')->name('remove_session');
    Route::get('/remove_session_fb', 'FacebookController@removeSession')->name('remove_session_fb');
    Route::get('editconnect', 'TwitterController@editConnect');
    Route::get('/add/fb/channel', 'FacebookController@getInfo');
    Route::get('/add/channel/fb', 'FacebookController@addChannel')->name('fb.add');
});
    /*================================================================================================*/
    /*========================BACKEND========================================================================*/
    /*========================ROUTES========================================================================*/
    /*========================FROM========================================================================*/
    /*========================HERE========================================================================*/
    /*================================================================================================*/
Route::group(['namespace'=>'Auth','prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/', 'AdminLoginController@showLoginForm')->name('show.LoginForm');
    Route::post('/login/validate', 'AdminLoginController@login')->name('login.validate');
    /*================================================================================================*/
    Route::get('/register', function (){
        return redirect()->route('admin.show.LoginForm');
    })->name('register.form');
    Route::post('/register/store', 'AdminRegisterController@store')->name('register.store');
    /*================================================================================================*/
    Route::get('/password/reset', 'AdminForgotPasswordController@index')->name('reset.form');
    Route::post('/email/reset', 'AdminForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset/{token}', 'AdminResetPasswordController@showResetForm')->name('password.reset.link');
    Route::post('/update/reset', 'AdminResetPasswordController@reset')->name('password.update');
    Route::post('/logout', 'AdminLoginController@logout')->name('user.logout');
});

    /*=============================Routes With===================================================================*/
    /*=============================MiddleWare===================================================================*/
Route::group(['middleware' => 'AdminUser','namespace'=>'backend','prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/dashboard', 'AdminUsersController@showDashboard')->name('dashboard');
    /*================================COUNTRY CRUD ROUTES ============================*/
    Route::get('/country','CountryController@index')->name('get.country');
    Route::get('/create/country', 'CountryController@create')->name('create.country');
    Route::post('/store/country', 'CountryController@store')->name('register.country');
    Route::get('/edit/country/{id}', 'CountryController@edit')->name('edit.country');
    Route::post('/delete/country/{id}', 'CountryController@delete')->name('destroy.country');
    /*================================INFLUENCERS USER CRUD ROUTES ============================*/
    Route::get('/users/influencers','InfluencersController@index')->name('getInfluencers');
    Route::get('/create/influencers', 'InfluencersController@create')->name('create.influencers');
    Route::post('/store/influencers', 'InfluencersController@store')->name('register.influencers');
    Route::get('/edit/influencers/{id}', 'InfluencersController@edit')->name('edit.influencers');
    Route::get('/history/influencers/{id}', 'InfluencersController@history')->name('history.influencers');
    Route::post('/delete/influencers/{id}', 'InfluencersController@delete')->name('destroy.influencers');
    Route::post('/status/influencers/{id}', 'InfluencersController@changeStatus')->name('update.status.influencers');
    /*================================ADMIN USER CRUD ROUTES ============================*/
    Route::get('/users/admin','AdminUsersController@index')->name('get.admin');
    Route::get('/create/admin', 'AdminUsersController@create')->name('create.admin');
    Route::post('/store/admin', 'AdminUsersController@store')->name('register.admin');
    Route::get('/edit/admin/{id}', 'AdminUsersController@edit')->name('edit.admin');
    Route::post('/delete/admin/{id}', 'AdminUsersController@delete')->name('destroy.admin');
    /*================================CAMPAIGN CRUD ROUTES ============================*/
    Route::get('/list/campaign', 'CampaignController@index')->name('get.campaign');
    Route::get('/create/campaign', 'CampaignController@create')->name('create.campaign');
    Route::post('/store/campaign', 'CampaignController@store')->name('register.campaign');
    Route::get('/edit/campaign/{id}', 'CampaignController@edit')->name('edit.campaign');
    Route::get('/manage/campaign/{id}', 'CampaignController@manage')->name('manage.campaign');
    Route::post('/manage/campaign/store', 'CampaignController@manageStore')->name('manage.campaign.store');
    Route::post('/delete/campaign/{id}', 'CampaignController@delete')->name('destroy.campaign');
    Route::post('/fetch/cities/{id}', 'CampaignController@fetchCities')->name('fetch.cities');
    Route::post('/fetch/influencers', 'CampaignController@fetchInfluencers')->name('fetch.influencers');
    Route::post('/manage/batchSize', 'CampaignController@batchSize')->name('batchsize.calculate');
    /*================================EMAIL=========== ============================*/
    Route::get('/cms/e-mail', 'emailController@index')->name('email.index');
    Route::get('/cms/e-mail/create', 'emailController@create')->name('email.create');
    Route::post('/cms/e-mail/store', 'emailController@store')->name('email.store');

app/Http/Controllers/backend/ContentManagementController.php
<?php

namespace App\Http\Controllers\backend;

use App\Model\backend\Country;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ContentManagementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

}

resources/views/backend/pages/contentManagement/addEmail.blade.php
<title>Add E-mail Address</title>
@include('backend.layouts.app')
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            &nbsp;&nbsp;&nbsp;Add E-mail Address
            <small>Preview</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li>Content Management</li>
            <li class="active"><a onclick="location.reload();" style="cursor: pointer">Add E-mail Address</a></li>
        </ol>
    </section>
    <section class="content">
        <div class="col-md-10">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Enter Details To Add E-mail Address</h3>
                </div>
                <!--================================ /.box-header =================================================-->
                <!--================================ form start ==================================================-->
                <form class="form-horizontal" id="addEmail" method="POST" action="{{route('admin.email.store')}}">
                    @csrf
                    <div class="box-body">
                        <div class="form-group">
                            <div class="col-sm-12">
                                <label>E-Mail:</label>
                                <input id="email" type="text" placeholder="Enter Email"
                                       class="form-control @error('email') is-invalid @enderror" name="email"
                                       value="{{ old('email') }}" autocomplete="email"
                                       style="text-transform:uppercase"
                                       autofocus>
                                @if($errors->has('email'))
                                    <span id="invalid-feedback" role="alert">
                                        <strong id="error" style="color: red">{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-12">
                                <label>Designation:</label>
                                <select id="designation" class="form-control @error('designation') is-invalid @enderror" name="designation">
                                    <option selected disabled>SELECT DESIGNATION</option>
                                    <option value="1">OVERALL ADMIN</option>
                                    <option value="2">CAMPAIGN MANAGER</option>
                                    <option value="3">SALES MANAGER</option>
                                </select>
                                {{--<input id="designation" type="text" placeholder="Enter Designation"
                                       class="form-control @error('designation') is-invalid @enderror" name="designation"
                                       value="{{ old('designation') }}" autocomplete="designation"
                                       style="text-transform:uppercase"
                                       autofocus>
                                @if($errors->has('designation'))
                                    <span id="invalid-feedback" role="alert">
                                        <strong id="error" style="color: red">{{ $errors->first('designation') }}</strong>
                                    </span>
                                @endif--}}
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <input type="submit" class="btn btn-primary btn-lg btn-block" value="Submit">
                    </div>
                </form>
            </div>
        </div>
    </section>
</div>
@jquery
@toastr_js
@toastr_render
@include('backend.layouts.sidebar')
@include('backend.layouts.foot')
@include('backend.pages.contentManagement.script')

resources/views/backend/pages/contentManagement/emailEdit.blade.php
<title>Edit E-mail Address</title>
@include('backend.layouts.app')
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            &nbsp;&nbsp;&nbsp;Edit E-mail Address
            <small>Preview</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li>Content Management</li>
            <li class="active"><a onclick="location.reload();" style="cursor: pointer">Edit E-mail Address</a></li>
        </ol>
    </section>
    <section class="content">
        <div class="col-md-10">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Enter Details To Edit E-mail Address</h3>
                </div>
                <!--================================ /.box-header =================================================-->
                <!--================================ form start ==================================================-->
                <form class="form-horizontal" id="addEmail" method="POST" action="{{route('admin.email.store')}}">
                    @csrf
                    <div class="box-body">
                        <div class="form-group">
                            <div class="col-sm-12">
                                <input type="hidden" name="id" value="{{$data[0]->id}}">
                                <label>E-Mail:</label>
                                <input id="email" type="text" placeholder="Enter Email"
                                       class="form-control @error('email') is-invalid @enderror" name="email"
                                       autocomplete="email"
                                       @if(isset($data))
                                       value="{{old('email') ? old('email') : ( ($data[0]->email) ? $data[0]->email : '' )}}"
                                       @endif
                                       style="text-transform:uppercase"
                                       autofocus>
                                @if($errors->has('email'))
                                    <span id="invalid-feedback" role="alert">
                                        <strong id="error" style="color: red">{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-12">
                                <label>Designation:</label>
                                <select id="designation" class="form-control @error('designation') is-invalid @enderror" name="designation">
                                    @if(isset($data[0]->designation))
                                        @if($data[0]->designation == 1)
                                            <option disabled>SELECT DESIGNATION</option>
                                            <option value="1" selected>OVERALL ADMIN</option>
                                            <option value="2">CAMPAIGN MANAGER</option>
                                            <option value="3">SALES MANAGER</option>
                                        @elseif($data[0]->designation == 2)
                                            <option disabled>SELECT DESIGNATION</option>
                                            <option value="1">OVERALL ADMIN</option>
                                            <option value="2" selected>CAMPAIGN MANAGER</option>
                                            <option value="3">SALES MANAGER</option>
                                        @elseif($data[0]->designation == 3)
                                            <option disabled>SELECT DESIGNATION</option>
                                            <option value="1">OVERALL ADMIN</option>
                                            <option value="2">CAMPAIGN MANAGER</option>
                                            <option value="3" selected>SALES MANAGER</option>
                                        @else
                                            <option disabled selected>SELECT DESIGNATION</option>
                                            <option value="1">OVERALL ADMIN</option>
                                            <option value="2">CAMPAIGN MANAGER</option>
                                            <option value="3">SALES MANAGER</option>
                                        @endif
                                    @else
                                        <option disabled selected>SELECT DESIGNATION</option>
                                        <option value="1">OVERALL ADMIN</option>
                                        <option value="2">CAMPAIGN MANAGER</option>
                                        <option value="3">SALES MANAGER</option>
                                    @endif
                                </select>
                                {{--<input id="designation" type="text" placeholder="Enter Designation"
                                       class="form-control @error('designation') is-invalid @enderror" name="designation"
                                       @if(isset($data))
                                       value="{{old('designation') ? old('designation') : ( ($data[0]->designation) ? $data[0]->designation : '' )}}"
                                       @endif
                                       style="text-transform:uppercase"
                                       autofocus>
                                @if($errors->has('designation'))
                                    <span id="invalid-feedback" role="alert">
                                        <strong id="error" style="color: red">{{ $errors->first('designation') }}</strong>
                                    </span>
                                @endif--}}
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <input type="submit" class="btn btn-primary btn-lg btn-block" value="Submit">
                    </div>
                </form>
            </div>
        </div>
    </section>
</div>
@jquery
@toastr_js
@toastr_render
@include('backend.layouts.sidebar')
@include('backend.layouts.foot')
@include('backend.pages.contentManagement.script')

resources/views/backend/pages/contentManagement/emailList.blade.php
<title>E-mail</title>
@include('backend.layouts.app')
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            &nbsp;&nbsp;&nbsp;E-mail
            <small>Preview</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li>Content Management</li>
            <li class="active"><a onclick="location.reload();" style="cursor: pointer">E-mail</a></li>
        </ol>
    </section>
    <section class="content">
        <div class="col-lg-12">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">List Of All Email </h3>
                    <a class="btn btn-primary pull-right" href="{{route('admin.email.create')}}" style="margin-right: 28px;">
                        <i class="glyphicon glyphicon-plus"></i>
                        Add New E-Mail
                    </a>
                </div>
                <div class="box-body">
                    <div class="table-responsive data-table-wrapper">
                        <table id="example" class="ui celled table">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>E-mail</th>
                                <th>Designation</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($obj as $k=> $data)
                            <tr>
                                <td>{{$data->id}}</td>
                                <td>{{$data->email}}</td>
                                <td>
                                    @if($data->designation == 1)
                                        OVERALL ADMIN
                                    @elseif($data->designation == 2)
                                        CAMPAIGN MANAGER
                                    @elseif($data->designation == 3)
                                        SALES MANAGER
                                    @endif
                                </td>
                                <td>
                                    <a class="btn btn-success btn-sm" href="{{route('admin.edit.email',$data->id)}}">
                                        <span class="glyphicon glyphicon-edit"></span> Edit
                                    </a>&nbsp;&nbsp;&nbsp;&nbsp;
                                    <button onclick="deleteEMAIL({{$data->id}})" data-id="{{$data->id}}" class="btn btn-danger btn-sm">
                                        <span class="glyphicon glyphicon-remove"></span> Delete
                                    </button>
                                </td>
                            </tr>
                            @endforeach
                            </tbody>
                            {{--<tfoot>
                            <tr>
                                <th>Id</th>
                                <th>E-mail</th>
                                <th>Designation</th>
                                <th>Action</th>
                            </tr>
                            </tfoot>--}}
                        </table>
                    </div>
                </div><!-- /.box-body -->
            </div>
        </div>
    </section>
</div>
@jquery
@toastr_js
@toastr_render
@include('backend.layouts.sidebar')
@include('backend.layouts.foot')
@include('backend.pages.contentManagement.script')
<script>
    $(document).ready(function() {
        var table = $('#example').DataTable( {
            lengthChange: false,
            buttons: [ 'copy', 'excel', 'pdf', 'colvis' ],
        } );
        table.buttons().container()
            .appendTo( $('div.eight.column:eq(0)', table.table().container()) );
    } );
</script>

resources/views/backend/pages/contentManagement/mailIndex.blade.php
<title>E-mail Templates</title>
@include('backend.layouts.app')
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            &nbsp;&nbsp;&nbsp;E-mail Templates
            <small>Preview</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li>Content Management</li>
            <li class="active"><a href="{{route('admin.mail.get')}}">E-mail Templates</a></li>
        </ol>
    </section>
    <section class="content">
        <div class="col-lg-12">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">List Of All Email </h3>
                    <a class="btn btn-primary pull-right" href="{{route('admin.email.template')}}" style="margin-right: 28px;">
                        <i class="glyphicon glyphicon-plus"></i>
                        Add New E-Mail Template
                    </a>
                </div>
                <div class="box-body">
                    <div class="table-responsive data-table-wrapper">
                        <table id="example" class="ui celled table">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>Template Events</th>
                                <th>For Whom</th>
                                <th>Status</th>
                                <th>FROM</th>
                                <th>CC</th>
                                <th>BCC</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $i = 0;?>
                            @foreach($data as $k=> $data1)
                                <tr>
                                    <td>{{$data[$i]->id}}</td>
                                    <td>{{$data[$i]->event}}</td>
                                    <td>
                                        @if($data[$i]->for_whom)
                                            Influencer
                                        @else
                                            Multiplier
                                        @endif
                                    </td>
                                    <td>
                                        @if($data[$i]->status)
                                            Active
                                        @else
                                            DeActive
                                        @endif
                                    </td>
                                    <td>{{$data[$i]->from}}</td>
                                    <td>{{$data[$i]->cc}}</td>
                                    <td>{{$data[$i]->bcc}}</td>
                                    <td>
                                        <a class="btn btn-success btn-sm" href="{{route('admin.email.template.edit',$data[$i]->id)}}">
                                            <span class="glyphicon glyphicon-edit"></span> Edit
                                        </a>&nbsp;&nbsp;&nbsp;&nbsp;
                                        <button class="btn btn-danger btn-sm" onclick="deleteTemplate({{$data[$i]->id}})">
                                            <span class="glyphicon glyphicon-remove"></span> Delete
                                        </button>
                                    </td>
                                </tr>
                                <?php $i++;?>
                            @endforeach
                            </tbody>
                            {{--<tfoot>
                            <tr>
                                <th>Id</th>
                                <th>E-mail Template Events</th>
                                <th>For Whom</th>
                                <th>Status</th>
                                <th>FROM</th>
                                <th>CC</th>
                                <th>BCC</th>
                                <th>Action</th>
                            </tr>
                            </tfoot>--}}
                        </table>
                    </div>
                </div><!-- /.box-body -->
            </div>
        </div>
    </section>
</div>
@jquery
@toastr_js
@toastr_render
@include('backend.layouts.sidebar')
@include('backend.layouts.foot')
@include('backend.pages.contentManagement.script')
<script>
    $(document).ready(function() {
        var table = $('#example').DataTable( {
            lengthChange: false,
            buttons: [ 'copy', 'excel', 'pdf', 'colvis' ],
        } );
        table.buttons().container()
            .appendTo( $('div.eight.column:eq(0)', table.table().container()) );
    } );
</script>