routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//use Illuminate\Routing\Route;
//use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect()->to('/login');
})->name('index');


Route::get('password/reset', [
    'as' => 'password.request',
    'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm'
]);

Route::get('/campaign', 'HomeController@index')->name('campaign');
Route::get('/influencer/account/{token}', 'frontend\InfluenceruserController@updateAccountStatus')->name('updateStatusAccount');

Route::get('connect', 'backend\TwitterController@connect');
Route::get('connectfb', 'backend\FacebookController@connect');
Route::post('getFacebookSession', 'backend\FacebookController@sessionData');
Route::post('getFacebookuser', 'backend\FacebookController@getFacebookuser');
Route::get('/redirecttwitter', 'SocialAuthTwitterController@redirect');
Route::get('/callbackUrl', 'SocialAuthTwitterController@callbackUrl');
Route::post('getSession', 'backend\TwitterController@sessionData');
Route::get('twittercallback', 'backend\TwitterController@callback')->name('twitter.callback');

Route::group(['namespace'=>'Auth'], function () {
    Route::post('/register/influencer', 'RegisterController@store')->name('register.influencer.user');  
    Route::get('/mail', 'RegisterController@mail')->name('mail');
    Route::get('/aa', 'RegisterController@aa')->name('aa');
    Route::get('/verifyMail', 'RegisterController@verifyMail')->name('verifyMail');
    Route::get('/adminVerifyMail', 'RegisterController@adminVerifyMail')->name('adminVerifyMail');
    Route::get('/influencer/register/', 'RegisterController@showRegistrationForm')->name('registerInf');
    Route::get('/redirect', 'FacebookController@redirect');
    Route::get('/callback', 'FacebookController@callback');
    Route::get('/city', 'RegisterController@getCity')->name('getCity');
});
Auth::routes();

Route::group(['middleware' => 'influencerUser','namespace'=>'frontend'], function () {
    Route::get('influencer/history/', 'InfluenceruserController@history')->name('influenceruser.history');
    Route::get('edit/profile/{id}', 'InfluenceruserController@edit')->name('influenceruser.edit');
    Route::post('/edit', 'InfluenceruserController@update')->name('influenceruser.update');
    Route::post('influencer/cp/', 'InfluenceruserController@changePassword')->name('influenceruser.cp');
    Route::get('facebookShare/verify/','InfluenceruserController@shareVerify')->name('facebookShare.verify');
    Route::post('twitter/verify/', 'InfluenceruserController@shareVerify')->name('twitter.verify');
    Route::post('fetch/cities/', 'InfluenceruserController@fetchCities')->name('influenceruser.fetchCities');
    Route::get('faq', 'InfluenceruserController@influenceruserFaq')->name('faq');
});

//Route::get('getFeed', 'backend\FacebookController@getFeed');
Route::group(['middleware' => 'influencerUser','namespace'=>'backend'], function () {
    Route::get('sharePost', 'FacebookController@shareCamping')->name('share');
    Route::get('shareTweet', 'TwitterController@shareTweet')->name('shareTweet');
    Route::get('postTweet/{id}', 'TwitterController@postTweet')->name('postTweet');
    Route::get('shareValidate', 'TwitterController@validateTweet')->name('validateTweet');
    Route::get('error', 'TwitterController@error')->name('twitter.error');
    Route::get('add_channel', 'TwitterController@addChannel')->name('twitter.add');
    Route::get('/remove/fb', 'FacebookController@removeChannel')->name('remove.fb.channel');
    Route::get('/remove/twitter', 'TwitterController@removeChannel')->name('remove.twitter.channel');
    Route::get('/remove_session', 'TwitterController@removeSession')->name('remove_session');
    Route::get('/remove_session_fb', 'FacebookController@removeSession')->name('remove_session_fb');
    Route::get('editconnect', 'TwitterController@editConnect');
    Route::get('/add/fb/channel', 'FacebookController@getInfo');
    Route::get('/add/channel/fb', 'FacebookController@addChannel')->name('fb.add');
});
    /*================================================================================================*/
    /*========================BACKEND========================================================================*/
    /*========================ROUTES========================================================================*/
    /*========================FROM========================================================================*/
    /*========================HERE========================================================================*/
    /*================================================================================================*/
Route::group(['namespace'=>'Auth','prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/', 'AdminLoginController@showLoginForm')->name('show.LoginForm');
    Route::post('/login/validate', 'AdminLoginController@login')->name('login.validate');
    /*================================================================================================*/
    Route::get('/register', function (){
        return redirect()->route('admin.show.LoginForm');
    })->name('register.form');
    Route::post('/register/store', 'AdminRegisterController@store')->name('register.store');
    /*================================================================================================*/
    Route::get('/password/reset', 'AdminForgotPasswordController@index')->name('reset.form');
    Route::post('/email/reset', 'AdminForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset/{token}', 'AdminResetPasswordController@showResetForm')->name('password.reset.link');
    Route::post('/update/reset', 'AdminResetPasswordController@reset')->name('password.update');
    Route::post('/logout', 'AdminLoginController@logout')->name('user.logout');
});

    /*=============================Routes With===================================================================*/
    /*=============================MiddleWare===================================================================*/
Route::group(['middleware' => 'AdminUser','namespace'=>'backend','prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/dashboard', 'AdminUsersController@showDashboard')->name('dashboard');
    /*================================COUNTRY CRUD ROUTES ============================*/
    Route::get('/country','CountryController@index')->name('get.country');
    Route::get('/create/country', 'CountryController@create')->name('create.country');
    Route::post('/store/country', 'CountryController@store')->name('register.country');
    Route::get('/edit/country/{id}', 'CountryController@edit')->name('edit.country');
    Route::post('/delete/country/{id}', 'CountryController@delete')->name('destroy.country');
    /*================================INFLUENCERS USER CRUD ROUTES ============================*/
    Route::get('/users/influencers','InfluencersController@index')->name('getInfluencers');
    Route::get('/create/influencers', 'InfluencersController@create')->name('create.influencers');
    Route::post('/store/influencers', 'InfluencersController@store')->name('register.influencers');
    Route::get('/edit/influencers/{id}', 'InfluencersController@edit')->name('edit.influencers');
    Route::get('/history/influencers/{id}', 'InfluencersController@history')->name('history.influencers');
    Route::post('/delete/influencers/{id}', 'InfluencersController@delete')->name('destroy.influencers');
    Route::post('/status/influencers/{id}', 'InfluencersController@changeStatus')->name('update.status.influencers');
    /*================================ADMIN USER CRUD ROUTES ============================*/
    Route::get('/users/admin','AdminUsersController@index')->name('get.admin');
    Route::get('/create/admin', 'AdminUsersController@create')->name('create.admin');
    Route::post('/store/admin', 'AdminUsersController@store')->name('register.admin');
    Route::get('/edit/admin/{id}', 'AdminUsersController@edit')->name('edit.admin');
    Route::post('/delete/admin/{id}', 'AdminUsersController@delete')->name('destroy.admin');
    /*================================CAMPAIGN CRUD ROUTES ============================*/
    Route::get('/list/campaign', 'CampaignController@index')->name('get.campaign');
    Route::get('/create/campaign', 'CampaignController@create')->name('create.campaign');
    Route::post('/store/campaign', 'CampaignController@store')->name('register.campaign');
    Route::get('/edit/campaign/{id}', 'CampaignController@edit')->name('edit.campaign');
    Route::get('/manage/campaign/{id}', 'CampaignController@manage')->name('manage.campaign');
    Route::post('/manage/campaign/store', 'CampaignController@manageStore')->name('manage.campaign.store');
    Route::post('/delete/campaign/{id}', 'CampaignController@delete')->name('destroy.campaign');
    Route::post('/fetch/cities/{id}', 'CampaignController@fetchCities')->name('fetch.cities');
    Route::post('/fetch/influencers', 'CampaignController@fetchInfluencers')->name('fetch.influencers');
    Route::post('/manage/batchSize', 'CampaignController@batchSize')->name('batchsize.calculate');
    /*================================EMAIL=========== ============================*/
    Route::get('/cms/e-mail', 'emailController@index')->name('email.index');
    Route::get('/cms/e-mail/create', 'emailController@create')->name('email.create');
    Route::post('/cms/e-mail/store', 'emailController@store')->name('email.store');

app/Http/Controllers/backend/AdminUsersController.php
<?php

namespace App\Http\Controllers\backend;

use App\Model\backend\Campaign;
use App\Model\frontend\influencerSocial;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\frontend\InfluencerUsers;
use App\Model\backend\AdminUser;
use Illuminate\Support\Facades\Hash;
USE Illuminate\Support\Facades\Mail;

class AdminUsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $country = AdminUser::get();
        return view('backend.pages.admins.adminList')->with(compact('country'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.pages.admins.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {	dd('hello');
        try{
            if($request->editid != '' || isset($request->editid)){
                $request->validate([
                    'user_name'=>'required|unique:adminuser,username,'.$request->editid,
                    'firstname'=>'required',
                    'lastname'=>'required',
                    'email'=>'required|email|unique:adminuser,email,'.$request->editid,
                    'skype'=>'required|unique:adminuser,skype,'.$request->editid,
                    'phone'=>'required|integer|unique:adminuser,phone,'.$request->editid,
                    'mobile'=>'required|integer|unique:adminuser,mobile,'.$request->editid,
                    'designation' => 'required|integer',
                ]);

                if($request->file('profile1') != null)
                {
                    $ext = $request->file('profile1')->getClientOriginalExtension();
                    $size = $request->file('profile1')->getSize();

                    $file = $request->file('profile1');
                    $pathfile = md5($file->getClientOriginalName(). time()).".".$ext;
                    $file->move(public_path('adminProfile'), $pathfile);
                }
                $obj = AdminUser::findOrFail($request->editid);
                $obj->username = $request['user_name'];
                $obj->firstname = $request['firstname'];
                $obj->lastname = $request['lastname'];
                $obj->email = $request['email'];
                $obj->skype = $request['skype'];
                $obj->phone = $request['phone'];
                $obj->mobile = $request['mobile'];
                $obj->au_ar_id = $request['designation'];

                if(isset($pathfile) && !empty($pathfile))
                    $obj->photo = $pathfile;

                $obj->save();

                toastr()->success('Admin has been Updated successfully!');
                return redirect()->route('admin.get.admin');
            }
            else{
                $request->validate([
                    'user_name'=>'required|unique:adminuser,username',
                    'firstname'=>'required',
                    'lastname'=>'required',
                    'email'=>'required|email|unique:adminuser,email',
                    'skype'=>'required|unique:adminuser,skype',
                    'phone'=>'required|integer|unique:adminuser,phone',
                    'mobile'=>'required|integer|unique:adminuser,mobile',
                    'pass'=>'required|min:6',
                    'retype_pass'=>'required|same:pass|min:6',
                    'profile'=>'required',
                    'designation' => 'required|integer',
                ]);
                if($request->file('profile') != null)
                {
                    $ext = $request->file('profile')->getClientOriginalExtension();
                    $size = $request->file('profile')->getSize();

                    $file = $request->file('profile');
                    $pathfile = md5($file->getClientOriginalName(). time()).".".$ext;
                    $file->move(public_path('adminProfile'), $pathfile);
                }

                $obj = new AdminUser();
                $obj->username = $request['user_name'];
                $obj->firstname = $request['firstname'];
                $obj->lastname = $request['lastname'];
                $obj->email = $request['email'];
                $obj->skype = $request['skype'];
                $obj->phone = $request['phone'];
                $obj->mobile = $request['mobile'];
                $obj->password =  Hash::make($request['retype_pass']);
                $obj->au_ar_id = "temp";
                $obj->photo = $pathfile;
                $obj->au_ar_id = $request['designation'];
                $obj->save();
                toastr()->success('Admin has been Generated successfully!');
                return redirect()->route('admin.get.admin');
            }
        }catch(Exception $e){

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $admin = AdminUser::find($id);
        return view('backend.pages.admins.edit')->with(compact('admin'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function delete($id){
        $admin = AdminUser::where('id',$id)->delete();
        return response()->json(1);
    }
    public function showDashboard()
    {

        $campaign['total'] = Campaign::get()->count();
        $campaign['active'] = Campaign::query()
            ->where('campaign_start','<=',Carbon::today()->toDateString())
            ->where('campaign_end','>=',Carbon::today()->toDateString())
            ->get()
            ->count();
        $campaign['upcoming'] = Campaign::query()
            ->where('campaign_start','>=',Carbon::today()->toDateString())->get()->count();
        $campaign['over'] = Campaign::query()->where('campaign_end','<=',Carbon::today()->toDateString())->get()->count();

        $influencer['total'] = InfluencerUsers::get()->count();
        $influencer['active'] = InfluencerUsers::query()->where('status',1)->count();
        $influencer['pending'] = influencerSocial::query()->where('isapporved',2)->count();
        $influencer['deactive'] = InfluencerUsers::query()->where('status',0)->count();

        return view('backend.pages.Dashboard')->with(compact('campaign','influencer'));
    }
}

resources/views/backend/layouts/app.blade.php
<!DOCTYPE html>
<html>
@include('backend.layouts.headercdn')
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <header class="main-header">
        <a href="{{route('admin.dashboard')}}" class="logo">
            <span class="logo-mini"><b>F-P</b></span>
            <span class="logo-lg"><b>FLY-POST</b></span>
        </a>
        <nav class="navbar navbar-static-top">
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    {{--@include('backend.layouts.message')--}}
                    {{--@include('backend.layouts.notification')--}}
                    @include('backend.layouts.task')
                    @include('backend.layouts.userdropbox')
                    {{--<li>
                        <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                    </li>--}}
                </ul>
            </div>
        </nav>
    </header>
@include('backend.layouts.navigation')

resources/views/backend/layouts/foot.blade.php
<div class="control-sidebar-bg"></div>
</div>
{{--<script src="{{ URL::asset('dash/bower_components/jquery/dist/jquery.min.js') }}"></script>--}}
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="{{ URL::asset('dash/bower_components/jquery-ui/jquery-ui.min.js') }}"></script>
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<script src="{{ URL::asset('dash/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<script src="{{ URL::asset('dash/bower_components/raphael/raphael.min.js') }}"></script>
<script src="{{ URL::asset('dash/bower_components/morris.js/morris.min.js') }}"></script>
<script src="{{ URL::asset('dash/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js') }}"></script>
<script src="{{ URL::asset('dash/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') }}"></script>
<script src="{{ URL::asset('dash/plugins/jvectormap/jquery-jvectormap-world-mill-en.js') }}"></script>
<script src="{{ URL::asset('dash/bower_components/jquery-knob/dist/jquery.knob.min.js') }}"></script>
<script src="{{ URL::asset('dash/bower_components/moment/min/moment.min.js') }}"></script>
<script src="{{ URL::asset('dash/bower_components/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
<script src="{{ URL::asset('dash/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
<script src="{{ URL::asset('dash/dist/js/adminlte.min.js') }}"></script>
<script src="{{ URL::asset('dash/dist/js/demo.js') }}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.15/js/bootstrap-multiselect.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.semanticui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/components/accordion.min.js" integrity="sha256-kt0Dfi+mrxAU+iYsfDrkROHrb55Hi0lVWC7MT46/xnU=" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.1/semantic.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.semanticui.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.colVis.min.js"></script>
</body>
</html>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/additional-methods.js"></script>
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
<script src="/vendor/unisharp/laravel-ckeditor/adapters/jquery.js"></script>
<script>
    $(window).on('load', function() {
        $('.content-wrapper').attr('style','min-height:1259px;');
        $('.ion').attr('style','margin-top:13px;');
    });
</script>

resources/views/backend/layouts/head.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{{ URL::asset('vendor/adminlte/vendor/bootstrap/dist/css/bootstrap.css')}}">
    <link rel="stylesheet" href="{{ URL::asset('vendor/adminlte/vendor/font-awesome/css/fontawesome.css')}}">
    <link rel="stylesheet" href="{{ URL::asset('vendor/adminlte/vendor/Ionicons/css/ionicons.css')}}">
    <link rel="stylesheet" href="{{ URL::asset('vendor/adminlte/dist/css/AdminLTE.min.css')}}">
    <link rel="stylesheet" href="{{ URL::asset('vendor/adminlte/plugins/iCheck/square/blue.css') }}">
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <style>
        .error{
            color: red;
        }
       
    </style>
</head>

resources/views/backend/layouts/message.blade.php
<li class="dropdown messages-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-envelope-o"></i>
        <span class="label label-success">4</span>
    </a>
    <ul class="dropdown-menu">
        <li class="header">You have 4 messages</li>
        <li>
            <!-- inner menu: contains the actual data -->
            <ul class="menu">
                <li><!-- start message -->
                    <a href="#">
                        <div class="pull-left">
                            <img src="{{URL::asset('dash/img/user4-128x128.jpg')}}" class="img-circle" alt="User Image">
                        </div>
                        <h4>
                            Support Team
                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                        </h4>
                        <p>Why not buy a new awesome theme?</p>
                    </a>
                </li>
                <!-- end message -->
                <li>
                    <a href="#">
                        <div class="pull-left">
                            <img src="{{URL::asset('dash/img/user4-128x128.jpg')}}" class="img-circle" alt="User Image">
                        </div>
                        <h4>
                            AdminLTE Design Team
                            <small><i class="fa fa-clock-o"></i> 2 hours</small>
                        </h4>
                        <p>Why not buy a new awesome theme?</p>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="pull-left">
                            <img src="{{URL::asset('dash/img/user4-128x128.jpg')}}" class="img-circle" alt="User Image">
                        </div>
                        <h4>
                            Developers
                            <small><i class="fa fa-clock-o"></i> Today</small>
                        </h4>
                        <p>Why not buy a new awesome theme?</p>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="pull-left">
                            <img src="{{URL::asset('dash/img/user4-128x128.jpg')}}" class="img-circle" alt="User Image">
                        </div>
                        <h4>
                            Sales Department
                            <small><i class="fa fa-clock-o"></i> Yesterday</small>
                        </h4>
                        <p>Why not buy a new awesome theme?</p>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="pull-left">
                            <img src="{{URL::asset('dash/img/user4-128x128.jpg')}}" class="img-circle" alt="User Image">
                        </div>
                        <h4>
                            Reviewers
                            <small><i class="fa fa-clock-o"></i> 2 days</small>
                        </h4>
                        <p>Why not buy a new awesome theme?</p>
                    </a>
                </li>
            </ul>
        </li>
        <li class="footer"><a href="#">See All Messages</a></li>
    </ul>
</li>

resources/views/backend/layouts/navigation.blade.php
<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ URL::asset('dash/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{ Auth::guard('admin')->user()->username}} </p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <form class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat" disabled>
                    <i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form>
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
            <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>Dashboard</a></li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Users</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('admin.get.admin')}}"><i class="fa fa-circle-o text-yellow"></i>List Admin</a></li>
                    <li><a href="{{route('admin.getInfluencers')}}"><i class="fa fa-circle-o text-yellow"></i>List Influencers</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Campaign Management</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('admin.get.campaign')}}"><i class="fa fa-circle-o text-yellow"></i>List Campaign</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Content Management</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('admin.get.country')}}"><i class="fa fa-circle-o text-yellow"></i>Country</a></li>
                    {{--<li><a href="{{route('admin.email.index')}}"><i class="fa fa-circle-o text-yellow"></i>E-Mail's</a></li>--}}
                    <li><a href="{{route('admin.mail.get')}}"><i class="fa fa-circle-o text-yellow"></i>Mail Template</a></li>
                    <li><a href="{{route('admin.faq.get')}}"><i class="fa fa-circle-o text-yellow"></i>FAQ's</a></li>
                </ul>
            </li>
        </ul>
    </section>
</aside>

resources/views/backend/layouts/userdropbox.blade.php
<li class="dropdown user user-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <img src="{{ URL::asset('dash/img/user2-160x160.jpg') }}" class="user-image" alt="User Image">
        <span class="hidden-xs">{{ Auth::guard('admin')->user()->email}}</span>
    </a>
    <ul class="dropdown-menu">
        <li class="user-header">
            <img src="{{ URL::asset('dash/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
            <p>
                {{ Auth::guard('admin')->user()->firstname}} {{ Auth::guard('admin')->user()->lastname}} - Admin
                <small>Member since Nov. 2019</small>
            </p>
        </li>
        {{--<li class="user-body">
            <div class="row">
                <div class="col-xs-4 text-center">
                    <a href="#">Followers</a>
                </div>
                <div class="col-xs-4 text-center">
                    <a href="#">Sales</a>
                </div>
                <div class="col-xs-4 text-center">
                    <a href="#">Friends</a>
                </div>
            </div>
        </li>--}}
        <li class="user-footer">
            <div class="pull-left">
                <a href="#" class="btn btn-default btn-flat">
                    <span class="glyphicon glyphicon-user"></span> Profile
                </a>
            </div>
            <div class="pull-right">
                <a class="btn btn-default btn-flat" href="{{ route('logout') }}"
                   onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();">
                    <span class="glyphicon glyphicon-log-out"></span>
                    Sign out
                </a>
                <form id="logout-form" action="{{ route('admin.user.logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</li>