routes/web.php
Route::post('getFacebookuser', 'backend\FacebookController@getFacebookuser');
Route::get('/redirecttwitter', 'SocialAuthTwitterController@redirect');
Route::get('/callbackUrl', 'SocialAuthTwitterController@callbackUrl');
Route::post('getSession', 'backend\TwitterController@sessionData');
Route::get('twittercallback', 'backend\TwitterController@callback')->name('twitter.callback');

Route::group(['namespace'=>'Auth'], function () {
    Route::post('/register/influencer', 'RegisterController@store')->name('register.influencer.user');  
    Route::get('/mail', 'RegisterController@mail')->name('mail');
    Route::get('/aa', 'RegisterController@aa')->name('aa');
    Route::get('/verifyMail', 'RegisterController@verifyMail')->name('verifyMail');
    Route::get('/adminVerifyMail', 'RegisterController@adminVerifyMail')->name('adminVerifyMail');
    Route::get('/influencer/register/', 'RegisterController@showRegistrationForm')->name('registerInf');
    Route::get('/redirect', 'FacebookController@redirect');
    Route::get('/callback', 'FacebookController@callback');
    Route::get('/city', 'RegisterController@getCity')->name('getCity');
});
Auth::routes();

Route::group(['middleware' => 'influencerUser','namespace'=>'frontend'], function () {
    Route::get('influencer/history/', 'InfluenceruserController@history')->name('influenceruser.history');
    Route::get('edit/profile/{id}', 'InfluenceruserController@edit')->name('influenceruser.edit');
    Route::post('/edit', 'InfluenceruserController@update')->name('influenceruser.update');
    Route::post('influencer/cp/', 'InfluenceruserController@changePassword')->name('influenceruser.cp');
    Route::get('facebookShare/verify/','InfluenceruserController@shareVerify')->name('facebookShare.verify');
    Route::post('twitter/verify/', 'InfluenceruserController@shareVerify')->name('twitter.verify');
    Route::post('fetch/cities/', 'InfluenceruserController@fetchCities')->name('influenceruser.fetchCities');
    Route::get('faq', 'InfluenceruserController@influenceruserFaq')->name('faq');
});

//Route::get('getFeed', 'backend\FacebookController@getFeed');
Route::group(['middleware' => 'influencerUser','namespace'=>'backend'], function () {
    Route::get('sharePost', 'FacebookController@shareCamping')->name('share');
    Route::get('shareTweet', 'TwitterController@shareTweet')->name('shareTweet');
    Route::get('postTweet/{id}', 'TwitterController@postTweet')->name('postTweet');
    Route::get('shareValidate', 'TwitterController@validateTweet')->name('validateTweet');
    Route::get('error', 'TwitterController@error')->name('twitter.error');
    Route::get('add_channel', 'TwitterController@addChannel')->name('twitter.add');
    Route::get('/remove/fb', 'FacebookController@removeChannel')->name('remove.fb.channel');
    Route::get('/remove/twitter', 'TwitterController@removeChannel')->name('remove.twitter.channel');
    Route::get('/remove_session', 'TwitterController@removeSession')->name('remove_session');
    Route::get('/remove_session_fb', 'FacebookController@removeSession')->name('remove_session_fb');
    Route::get('editconnect', 'TwitterController@editConnect');
    Route::get('/add/fb/channel', 'FacebookController@getInfo');
    Route::get('/add/channel/fb', 'FacebookController@addChannel')->name('fb.add');
});
    /*================================================================================================*/
    /*========================BACKEND========================================================================*/
    /*========================ROUTES========================================================================*/
    /*========================FROM========================================================================*/
    /*========================HERE========================================================================*/
    /*================================================================================================*/
Route::group(['namespace'=>'Auth','prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/', 'AdminLoginController@showLoginForm')->name('show.LoginForm');
    Route::post('/login/validate', 'AdminLoginController@login')->name('login.validate');
    /*================================================================================================*/
    Route::get('/register', function (){
        return redirect()->route('admin.show.LoginForm');
    })->name('register.form');
    Route::post('/register/store', 'AdminRegisterController@store')->name('register.store');
    /*================================================================================================*/
    Route::get('/password/reset', 'AdminForgotPasswordController@index')->name('reset.form');
    Route::post('/email/reset', 'AdminForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset/{token}', 'AdminResetPasswordController@showResetForm')->name('password.reset.link');
    Route::post('/update/reset', 'AdminResetPasswordController@reset')->name('password.update');
    Route::post('/logout', 'AdminLoginController@logout')->name('user.logout');
});

    /*=============================Routes With===================================================================*/
    /*=============================MiddleWare===================================================================*/
Route::group(['middleware' => 'AdminUser','namespace'=>'backend','prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/dashboard', 'AdminUsersController@showDashboard')->name('dashboard');
    /*================================COUNTRY CRUD ROUTES ============================*/
    Route::get('/country','CountryController@index')->name('get.country');
    Route::get('/create/country', 'CountryController@create')->name('create.country');
    Route::post('/store/country', 'CountryController@store')->name('register.country');
    Route::get('/edit/country/{id}', 'CountryController@edit')->name('edit.country');
    Route::post('/delete/country/{id}', 'CountryController@delete')->name('destroy.country');
    /*================================INFLUENCERS USER CRUD ROUTES ============================*/
    Route::get('/users/influencers','InfluencersController@index')->name('getInfluencers');
    Route::get('/create/influencers', 'InfluencersController@create')->name('create.influencers');
    Route::post('/store/influencers', 'InfluencersController@store')->name('register.influencers');
    Route::get('/edit/influencers/{id}', 'InfluencersController@edit')->name('edit.influencers');
    Route::get('/history/influencers/{id}', 'InfluencersController@history')->name('history.influencers');
    Route::post('/delete/influencers/{id}', 'InfluencersController@delete')->name('destroy.influencers');
    Route::post('/status/influencers/{id}', 'InfluencersController@changeStatus')->name('update.status.influencers');
    /*================================ADMIN USER CRUD ROUTES ============================*/
    Route::get('/users/admin','AdminUsersController@index')->name('get.admin');
    Route::get('/create/admin', 'AdminUsersController@create')->name('create.admin');
    Route::post('/store/admin', 'AdminUsersController@store')->name('register.admin');
    Route::get('/edit/admin/{id}', 'AdminUsersController@edit')->name('edit.admin');
    Route::post('/delete/admin/{id}', 'AdminUsersController@delete')->name('destroy.admin');
    /*================================CAMPAIGN CRUD ROUTES ============================*/
    Route::get('/list/campaign', 'CampaignController@index')->name('get.campaign');
    Route::get('/create/campaign', 'CampaignController@create')->name('create.campaign');
    Route::post('/store/campaign', 'CampaignController@store')->name('register.campaign');
    Route::get('/edit/campaign/{id}', 'CampaignController@edit')->name('edit.campaign');
    Route::get('/manage/campaign/{id}', 'CampaignController@manage')->name('manage.campaign');
    Route::post('/manage/campaign/store', 'CampaignController@manageStore')->name('manage.campaign.store');
    Route::post('/delete/campaign/{id}', 'CampaignController@delete')->name('destroy.campaign');
    Route::post('/fetch/cities/{id}', 'CampaignController@fetchCities')->name('fetch.cities');
    Route::post('/fetch/influencers', 'CampaignController@fetchInfluencers')->name('fetch.influencers');
    Route::post('/manage/batchSize', 'CampaignController@batchSize')->name('batchsize.calculate');
    /*================================EMAIL=========== ============================*/
    Route::get('/cms/e-mail', 'emailController@index')->name('email.index');
    Route::get('/cms/e-mail/create', 'emailController@create')->name('email.create');
    Route::post('/cms/e-mail/store', 'emailController@store')->name('email.store');
    Route::post('/cms/e-mail/delete/{id}', 'emailController@delete')->name('destroy.mail');
    Route::get('/cms/e-mail/edit/{id}', 'emailController@edit')->name('edit.email');
    /*================================MAIL Templates ============================*/
    Route::get('/cms/mail/template/list', 'EmailTemplateController@index')->name('mail.get');
    Route::get('/cms/mail/template', 'EmailTemplateController@create')->name('email.template');
    Route::get('/cms/mail/edit/{id}', 'EmailTemplateController@edit')->name('email.template.edit');
    Route::post('/cms/mail/store', 'EmailTemplateController@store')->name('email.template.store');
    Route::post('/cms/mail/delete/{id}', 'EmailTemplateController@delete')->name('email.template.destroy');
    /*================================FAQ's Templates ============================*/
    Route::get('/cms/faq/list', 'FaqController@index')->name('faq.get');
    Route::get('/cms/faq/create', 'FaqController@create')->name('faqs.create');
    Route::post('/cms/faq/store', 'FaqController@store')->name('faqs.store');
    Route::get('/cms/faq/{id}', 'FaqController@edit')->name('edit.faqs');

app/Http/Controllers/backend/CountryController.php
<?php

namespace App\Http\Controllers\backend;

use App\Model\backend\Country;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CountryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        $country = Country::get();
        return view('backend.pages.country.country')->with(compact('country'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.pages.country.addCountry');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            if($request->editid != '' || isset($request->editid))
            {
                $this->validate($request,[
                    'country'=>'required|unique:countries,name,'.$request->editid,
                    'country_code'=>'required',
                    'phoneCode'=>'required|integer',
                ]);
                $country1 = Country::findOrFail($request->editid);
                $country1->name = $request->country;
                $country1->code = $request->country_code;
                $country1->phonecode = $request->phoneCode;
                $country1->save();
                toastr()->success('Country has been Updated successfully!');
                return redirect()->route('admin.get.country');
            }else{
                $this->validate($request,[
                    'country'=>'required|unique:countries,name',
                    'country_code'=>'required',
                    'phoneCode'=>'required|integer',
                ]);
                $country1 = new Country();
                $country1->name = $request->country;
                $country1->code = $request->country_code;
                $country1->phonecode = $request->phoneCode;
                $country1->save();
            }
            toastr()->success('Country has been Added successfully!');
            return redirect()->route('admin.get.country');
        }catch (Exception $e){
            toastr()->error('Country has not been Added!');
            return redirect()->route('admin.get.country');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $country = Country::find($id);
        return view('backend.pages.country.editCountry')->with(compact('country'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function delete($id){
        $destroy = Country::where('id',$id)->delete();
        return response()->json(1);
    }
}

resources/views/backend/pages/country/addCountry.blade.php
<title>Add Country</title>
@include('backend.layouts.app')
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            &nbsp;&nbsp;&nbsp;Country Registration Form
            <small>Preview</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li>Country</li>
            <li class="active"><a href="{{route('admin.create.country')}}">List Country</a></li>
        </ol>
    </section>
    <section class="content">
        <div class="col-md-10">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Enter Details Of The Country</h3>
                </div>
                <!--================================ /.box-header =================================================-->
                <!--================================ form start ==================================================-->
                <form class="form-horizontal" method="POST" id="CountryRegister" action="{{route('admin.register.country')}}">
                    @csrf
                    <div class="box-body">
                        <div class="form-group">
                            <div class="col-sm-12">
                                <label>Coountry:</label>
                                <input id="country" type="text" placeholder="Country Name"
                                       class="form-control @error('country') is-invalid @enderror" name="country"
                                       value="{{ old('country') }}" autocomplete="firstname"
                                       style="text-transform:uppercase"
                                       autofocus>
                                @if($errors->has('country'))
                                    <span id="invalid-feedback" role="alert">
                                        <strong id="error" style="color: red">{{ $errors->first('country') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-12">
                                <label>Country Code:</label>
                                <input id="code" type="text" placeholder="Country Code"
                                       class="form-control @error('email') is-invalid @enderror" name="country_code"
                                       value="{{ old('country_code') }}" autocomplete="email" style="text-transform:uppercase">
                                @if($errors->has('country_code'))
                                    <span id="invalid-feedback" role="alert">
                                        <strong id="error" style="color: red">{{ $errors->first('country_code') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-12">
                                <label>Phone Code:</label>
                                <input id="phoneCode" type="text" class="form-control"
                                       placeholder="Phone Code" name="phoneCode"
                                       autocomplete="new-password">
                                @if($errors->has('phoneCode'))
                                    <span id="invalid-feedback" role="alert">
                                        <strong id="error"
                                                style="color: red">{{ $errors->first('phoneCode') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <input type="submit" class="btn btn-primary btn-lg btn-block" value="Add Country">
                    </div>
                </form>
            </div>
        </div>
    </section>
</div>
@jquery
@toastr_js
@toastr_render
@include('backend.layouts.sidebar')
@include('backend.layouts.foot')
@include('backend.pages.country.script')

resources/views/backend/pages/country/country.blade.php
<title>Country List</title>
<head>
    <link rel="stylesheet" href="{{ URL::asset('css/switch.css') }}">
</head>
@include('backend.layouts.app')
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            &nbsp;&nbsp;&nbsp;Country
            <small>Preview</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li>Content Management</li>
            <li class="active"><a href="{{route('admin.get.country')}}">List Country</a></li>
        </ol>
    </section>
    <section class="content">
        <div class="col-lg-12">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">List Of All Country </h3>
                    <a class="btn btn-primary pull-right" href="{{route('admin.create.country')}}" style="margin-right: 28px;">
                        <i class="glyphicon glyphicon-plus"></i>
                        Add New Country
                    </a>
                </div>
                <div class="box-body">
                    <div class="table-responsive data-table-wrapper">
                        <table id="example" class="ui celled table">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>Country Name</th>
                                <th>Country Code</th>
                                <th>Phone Code</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($country as $k=> $data)
                                <tr>
                                    <td>{{$data->id}}</td>
                                    <td>{{$data->name}}</td>
                                    <td>{{$data->code}}</td>
                                    <td>{{$data->phonecode}}</td>
                                    <td>
                                        <a class="btn btn-success btn-sm" href="{{route('admin.edit.country',$data->id)}}">
                                            <span class="glyphicon glyphicon-edit"></span> Edit
                                        </a>&nbsp;&nbsp;&nbsp;&nbsp;
                                        <button onclick="deleteCountry({{$data->id}})" data-id="{{$data->id}}" class="btn btn-danger btn-sm">
                                            <span class="glyphicon glyphicon-remove"></span> Delete
                                        </button>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div><!-- /.box-body -->
            </div>
        </div>
    </section>
</div>
@jquery
@toastr_js
@toastr_render
@include('backend.layouts.sidebar')
@include('backend.layouts.foot')
@include('backend.pages.country.script')
<script>
    $(document).ready(function() {
        var table = $('#example').DataTable( {
            lengthChange: false,
            buttons: [ 'copy', 'excel', 'pdf', 'colvis' ],
        } );
        table.buttons().container()
            .appendTo( $('div.eight.column:eq(0)', table.table().container()) );
    } );
</script>

resources/views/backend/pages/country/editCountry.blade.php
<title>Edit Country</title>
@include('backend.layouts.app')
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            &nbsp;&nbsp;&nbsp;Update Country Form
            <small>Preview</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li>Country</li>
            <li class="active"><a onclick="location.reload()" style="cursor: pointer">Edit Country</a></li>
        </ol>
    </section>
    <section class="content">
        <div class="col-md-10">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Update Details Of The Country</h3>
                </div>
                <!--================================ /.box-header =================================================-->
                <!--================================ form start ==================================================-->
                <form class="form-horizontal" method="POST" id="CountryRegister" action="{{route('admin.register.country')}}">
                    @csrf
                    <div class="box-body">
                        <div class="form-group">
                            <div class="col-sm-12">
                                <input type="hidden" name="editid" value="{{$country->id}}">
                                <label>Country Name:</label>
                                <input id="country" type="text" placeholder="Country Name"
                                       class="form-control @error('country') is-invalid @enderror" name="country"
                                       @if(isset($country->name))
                                       value="{{old('country') ? old('country') : ( ($country->name) ? $country->name : '' )}}"
                                       @endif
                                       style="text-transform:uppercase"
                                       autofocus>
                                @if($errors->has('country'))
                                    <span id="invalid-feedback" role="alert">
                                        <strong id="error" style="color: red">{{ $errors->first('country') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-12">
                                <label>Country Code:</label>
                                <input id="code" type="text" placeholder="Country Code"
                                       class="form-control @error('email') is-invalid @enderror" name="country_code"
                                       @if(isset($country->code))
                                       value="{{old('country_code') ? old('country_code') : ( ($country->code) ? $country->code : '' )}}"
                                       @endif
                                       autocomplete="email" style="text-transform:uppercase">
                                @if($errors->has('country_code'))
                                    <span id="invalid-feedback" role="alert">
                                        <strong id="error" style="color: red">{{ $errors->first('country_code') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        {{--<div class="form-group">
                            <div class="col-sm-6">
                                <input id="numberCode" type="text" placeholder="Number Code"
                                       class="form-control @error('numCode') is-invalid @enderror" name="numCode"
                                       @if(isset($country->numcode))
                                            value="{{old('numCode') ? old('numCode') : ( ($country->numcode) ? $country->numcode : '' )}}"
                                       @endif
                                       autocomplete="new-password">
                                @if($errors->has('numCode'))
                                    <span id="invalid-feedback" role="alert">
                                        <strong id="error" style="color: red">*{{ $errors->first('numCode') }}</strong>
                                    </span>
                                @endif
                            </div>--}}
                        <div class="form-group">
                            <div class="col-sm-12">
                                <label>Phone Code:</label>
                                <input id="phoneCode" type="text" class="form-control"
                                       placeholder="Phone Code" name="phoneCode"
                                       @if(isset($country->phonecode))
                                       value="{{old('phoneCode') ? old('phoneCode') : ( ($country->phonecode) ? $country->phonecode : '' )}}"
                                       @endif
                                       autocomplete="new-password">
                                @if($errors->has('phoneCode'))
                                    <span id="invalid-feedback" role="alert">
                                        <strong id="error" style="color: red">{{ $errors->first('phoneCode') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <input type="submit" class="btn btn-primary btn-lg btn-block" value="Edit Country">
                    </div>
                </form>
            </div>
        </div>
    </section>
</div>
@jquery
@toastr_js
@toastr_render
@include('backend.layouts.sidebar')
@include('backend.layouts.foot')
@include('backend.pages.country.script')

resources/views/backend/pages/country/script.blade.php
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/additional-methods.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>
    function deleteCountry(input) {
        var id = input;
        var url = "{{route('admin.destroy.country', ":id")}}";
        url = url.replace(':id', id);

        swal({
            title: "Are you sure?",
            text: "You will not be able to recover this Country!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        dataType: "json",
                        type: "POST",
                        url: url,
                        data: {
                            "_token": "{{ csrf_token() }}",
                            "id": id,
                        },
                        success: function (data) {
                            location.reload();
                        }
                    });
                }
            });
    }
</script>
<script>
    $(document).ready(function () {
        $("#CountryRegister").validate({
            rules:{
                country_code:{
                    required:true,
                },
                country:{
                    required:true
                },
                numCode:{
                    required:true,
                    integer:true,
                },
                phoneCode:{
                    required:true,
                    integer:true,
                }
            },
            messages:{
                country_code:{
                    required:"Please Enter Country Code",
                },
                country:{
                    required:"Please Enter Country Name"
                },
                numCode:{
                    required:"Please Enter Number-Code",
                    integer:"Please Enter Valid Number-Code",
                },
                phoneCode:{
                    required:"Please Enter Phone-Code",
                    integer:"Please Enter Valid Phone-Code",
                }
            }
        });
    });
</script>